## Windows
KoNLPy 설치  
https://d-e-v.tistory.com/9  

KoNLPy 설치 후, module 'tweepy' has no attribute 'StreamListener' 에러가 발생한 경우,  
```
!pip install tweepy==3.10.0
```
상기 명령어를 통해 tweepy 버전을 낮춘 후, 실행해본다.`(주피터 노트북 재시작 필요)`

- JVM 세팅도 해주어야 함..

## MacOS
KoNLPy 설치
```
python3 -m pip install konlpy
python3 -m pup install tweepy==3.10.0
```
- JVM 설치 (https://www.oracle.com/java/technologies/downloads/#jdk17-mac)

JVM 환경변수 설정에 주의할 것! (고급 시스템 설정 보기)

## 1. KKMA (꼬꼬마)
서울대학교 IDS(Intelligent Data Systems) 연구실에서 자연어 처리를 위해 개발한 한국어 stemmer


--sys.version—
3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]


In [1]:
from konlpy.tag import Kkma
kkma = Kkma()
text = "아버지가 방에 들어가십니다."

#형태소 추출
morphs = kkma.morphs(text)
print(morphs)

#형태소와 품사 태그 셋 추출
pos = kkma.pos(text)
print(pos)

['아버지', '가', '방', '에', '들어가', '시', 'ㅂ니다', '.']
[('아버지', 'NNG'), ('가', 'JKS'), ('방', 'NNG'), ('에', 'JKM'), ('들어가', 'VV'), ('시', 'EPH'), ('ㅂ니다', 'EFN'), ('.', 'SF')]


## 2. Komoran (코모란)

In [23]:
from konlpy.tag import Komoran
f= open('./user_dic.tsv','r', encoding='utf-8', newline='')


# 탭 확인 코드
#with open('./user_dic.tsv', 'r',encoding='utf-8') as f:
#    for line in f:
#        print(line.strip().replace('\t', '<tab>'))
        
komoran = Komoran(userdic='./user_dic.tsv')
text = "우리 챗봇은 엔엘피를 좋아해."

#형태소 추출
morphs = komoran.morphs(text)
print(morphs)

#형태소와 품사 태그 셋 추출
pos = komoran.pos(text)
print(pos)

print("-"*10)

nouns = komoran.nouns(text)
print(nouns)

엔엘피	NNG

엔엘피<tab>NNG
['우리', '챗봇은', '엔엘피', '를', '좋아하', '아', '.']
[('우리', 'NP'), ('챗봇은', 'NA'), ('엔엘피', 'NNG'), ('를', 'JKO'), ('좋아하', 'VV'), ('아', 'EF'), ('.', 'SF')]
----------
['엔엘피']


## 3. Okt (Open-source Korean Text Processor)

In [25]:
from konlpy.tag import Okt
okt = Okt()
text = "아버지가 엔엘피를 좋아하십니다."

#형태소 추출
morphs = okt.morphs(text)
print(morphs)

#형태소와 품사 태그 셋 추출
pos = okt.pos(text)
print(pos)



['아버지', '가', '엔엘', '피', '를', '좋아하십니다', '.']
[('아버지', 'Noun'), ('가', 'Josa'), ('엔엘', 'Noun'), ('피', 'Noun'), ('를', 'Josa'), ('좋아하십니다', 'Adjective'), ('.', 'Punctuation')]


## 워드임베딩 ) 단어임베딩 ) 원-핫 인코딩

In [31]:
from konlpy.tag import Komoran
import numpy as np

komoran = Komoran()
text = "오늘 날씨는 구름이 많아요."

nouns = komoran.nouns(text)
print(nouns)

dics={}
for word in nouns:
    if word not in dics.keys():
        dics[word] = len(dics)
print(dics)

#원-핫 인코딩
nb_classes = len(dics)
targets = list(dics.values())

print(targets)
one_hot_targets = np.eye(nb_classes)[targets]
print(one_hot_targets)

['오늘', '날씨', '구름']
{'오늘': 0, '날씨': 1, '구름': 2}
[0, 1, 2]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
